"use client";

import React, { createContext, useContext, useEffect, useState } from "react";

export type Language = "ku" | "kmr" | "ar" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  dir: "ltr" | "rtl";
  t: (key: keyof typeof translations.en) => string;
}

const translations = {
  en: {
    home: "Home",
    products: "Products",
    brands: "Brands",
    brewing_guide: "Brewing",
    news: "Journal",
    premiumCoffeeEquipment: "Premium Coffee Equipment",
    collections: "Collections",
    about: "About",
    contact: "Contact",
    search: "Search...",
    searchProducts: "Search products...",
    bestSellers: "Signature Collection",
    curatedSelection: "Curated Selection",
    curatedSelectionDesc: "Discover carefully selected coffee tools and accessories from world-class brands.",
    exploreAll: "Explore Full Collection",
    addToCart: "Add to Cart",
    orderWhatsApp: "Order via WhatsApp",
    orderWithDetails: "Direct Order via WhatsApp (Cash on Delivery)",
    payOnlineCard: "Pay Online (Card)",
    orderModalDesc: "Please enter your address and phone number to send your order via WhatsApp. Payment is cash upon delivery.",
    quickOrderWhatsApp: "Quick Checkout",
    directOrderNoDetails: "Instant Chat Inquiry",
    fullName: "Full Name",
    phoneNumber: "Phone Number",
    city: "City / Region",
    address: "Detailed Address",
    cancel: "Cancel",
    confirmOrder: "Send Order via WhatsApp",
    fillAllFields: "Please fill in all fields",
    inStock: "In Stock",
    outOfStock: "Out of Stock",
    soldOut: "Sold Out",
    bestSeller: "Best Seller",
    newArrival: "NEW",
    reviews: "reviews",
    relatedProducts: "Related Products",
    youMayAlsoLike: "You May Also Like",
    description: "Description",
    allRightsReserved: "All rights reserved.",
    language: "Language",
    english: "English",
    arabic: "العربية",
    kurdish: "کوردی",
    heroTitlePart1: "We Select",
    heroTitlePart2: "",
    heroTitlePart3: "The Best",
    heroTitlePart4: "",
    heroSubtitle: "Timeless tools. Thoughtful design. Better coffee, every day.",
    exploreCollection: "Explore Collection",
    watchOurStory: "Watch Our Story",
    typesOfCoffee: "Types of Making Coffee",
    exploreMethods: "Explore the different methods of brewing to find the perfect cup for your taste.",
    shopTools: "Shop Tools",
    newsletter: "Newsletter",
    newsletterDesc: "Subscribe to receive updates, access to exclusive deals, and more.",
    subscribe: "Subscribe",
    quickLinks: "Quick Links",
    contactUs: "Contact Us",
    yourWishlistEmpty: "Your wishlist is empty",
    wishlistEmptyDesc: "Looks like you haven't saved any products yet. Browse our collection and click the heart icon to save items here.",
    exploreProducts: "Explore Products",
    myWishlist: "My Wishlist",
    savedProducts: "Products you have saved for later.",
    items: "items",
    item: "item",
    noProductsFound: "No products found",
    tryAdjusting: "Try adjusting your search or category.",
    filter: "Filter:",
    allCategories: "All Categories",
    allProducts: "All Products",
    allProductsDesc: "Explore our complete collection of premium coffee tools and equipment.",
    footerDesc: "Diar Selection is the premium destination for authentic specialty coffee equipment. We carefully curate the world's finest tools to elevate your daily coffee ritual.",
    connect: "Connect",
    visitUs: "Visit Us",
    viewProduct: "Buy Product",
    aboutSubtitle: "About Diar Selection",
    aboutTitle1: "Crafted for",
    aboutTitle2: "People Who",
    aboutTitle3: "Live for Coffee.",
    aboutP1: "Diar Selection was founded with a single mission: to bring the world's finest specialty coffee equipment to enthusiasts who demand nothing but the best.",
    aboutP2: "We carefully curate every product in our collection, working directly with brands like Fellow, Timemore, Hario, and 1Zpresso to ensure authenticity and quality. Each tool is selected not just for its function, but for the experience it creates.",
    aboutP3: "Our commitment goes beyond selling products. We are building a community of coffee lovers who share our passion for the perfect cup — and the premium tools that make it possible.",
    aboutVal1Title: "Curated Excellence",
    aboutVal1Desc: "Every product is hand-picked by coffee professionals who understand what makes equipment truly exceptional.",
    aboutVal2Title: "Authenticity Guaranteed",
    aboutVal2Desc: "We work directly with brands and authorized distributors. Every item is 100% original with full manufacturer warranty.",
    aboutVal3Title: "Trust & Transparency",
    aboutVal3Desc: "Honest recommendations. No compromises. We only sell products we personally use and believe in.",
    aboutVal4Title: "Passion in Every Detail",
    aboutVal4Desc: "We're more than a store — we're a community fueled by a deep love for specialty coffee and the rituals around it.",
    aboutJoin: "Join thousands of coffee enthusiasts who trust Diar Selection.",
    getInTouch: "Get in Touch",
    contactTitle1: "We'd Love to",
    contactTitle2: "Hear From You",
    phone: "Phone",
    phoneSub: "Sat - Sun, 9AM - 8PM",
    instagram: "Instagram",
    followUs: "Follow us",
    whatsapp: "WhatsApp",
    chatWithUs: "Chat with us",
    quickResponse: "Quick response",
    location: "Location",
    locationDetail: "Slemani, Kurdistan, Iraq",
    visitOurStore: "Visit our store",
    whatsappChat: "WhatsApp Chat",
    slemaniLocation: "Slemani, Kurdistan",
    iraq: "Iraq",
    searchCollection: "Search our collection...",
  },
  ar: {
    home: "الرئيسية",
    products: "المنتجات",
    brands: "العلامات التجارية",
    brewing_guide: "التحضير",
    news: "المدونة",
    premiumCoffeeEquipment: "أدوات قهوة فاخرة",
    collections: "المجموعات",
    about: "من نحن",
    contact: "تواصل معنا",
    search: "بحث...",
    searchProducts: "ابحث عن المنتجات...",
    bestSellers: "المجموعة المميزة",
    curatedSelection: "اختياراتنا لك",
    curatedSelectionDesc: "اكتشف أدوات وإكسسوارات القهوة المختارة بعناية من ماركات عالمية.",
    exploreAll: "استكشف المجموعة الكاملة",
    addToCart: "أضف إلى السلة",
    orderWhatsApp: "اطلب عبر واتساب",
    orderWithDetails: "طلب مباشر عبر واتساب (الدفع كاش عند الاستلام)",
    payOnlineCard: "الدفع عبر الإنترنت (كارت)",
    orderModalDesc: "يرجى كتابة عنوانك ورقم هاتفك لإرسال الطلب عبر واتساب. يكون الدفع نقداً (كاش) عند استلام الطلب.",
    quickOrderWhatsApp: "شراء سريع عبر واتساب",
    directOrderNoDetails: "استفسار مباشر عبر المحادثة",
    fullName: "الاسم الكامل",
    phoneNumber: "رقم الهاتف",
    city: "المدينة / المنطقة",
    address: "العنوان بالتفصيل",
    cancel: "إلغاء",
    confirmOrder: "إرسال الطلب عبر واتساب",
    fillAllFields: "يرجى ملء جميع الحقول",
    inStock: "متوفر",
    outOfStock: "غير متوفر",
    soldOut: "نفذ",
    bestSeller: "الأكثر مبيعاً",
    newArrival: "جديد",
    reviews: "مراجعات",
    relatedProducts: "منتجات ذات صلة",
    youMayAlsoLike: "قد يعجبك أيضاً",
    description: "الوصف",
    allRightsReserved: "جميع الحقوق محفوظة.",
    language: "اللغة",
    english: "English",
    arabic: "العربية",
    kurdish: "کوردی",
    heroTitlePart1: "نختار",
    heroTitlePart2: "",
    heroTitlePart3: "الأفضل",
    heroTitlePart4: "",
    heroSubtitle: "أدوات خالدة. تصميم مدروس. قهوة أفضل، كل يوم.",
    exploreCollection: "استكشف المجموعة",
    watchOurStory: "شاهد قصتنا",
    typesOfCoffee: "طرق تحضير القهوة",
    exploreMethods: "استكشف الطرق المختلفة للتحضير للعثور على الكوب المثالي لذوقك.",
    shopTools: "تسوق الأدوات",
    newsletter: "النشرة الإخبارية",
    newsletterDesc: "اشترك لتلقي التحديثات والوصول إلى العروض الحصرية والمزيد.",
    subscribe: "اشتراك",
    quickLinks: "روابط سريعة",
    contactUs: "اتصل بنا",
    yourWishlistEmpty: "قائمة أمنياتك فارغة",
    wishlistEmptyDesc: "يبدو أنك لم تقم بحفظ أي منتجات بعد. تصفح مجموعتنا وانقر على أيقونة القلب لحفظ العناصر هنا.",
    exploreProducts: "استكشف المنتجات",
    myWishlist: "قائمة أمنياتي",
    savedProducts: "المنتجات التي حفظتها لوقت لاحق.",
    items: "عناصر",
    item: "عنصر",
    noProductsFound: "لم يتم العثور على منتجات",
    tryAdjusting: "حاول تعديل البحث أو الفئة.",
    filter: "تصفية:",
    allCategories: "جميع الفئات",
    allProducts: "جميع المنتجات",
    allProductsDesc: "استكشف مجموعتنا الكاملة من أدوات ومعدات القهوة الفاخرة.",
    footerDesc: "ديار سيلكشن هي الوجهة الفاخرة لأدوات القهوة المختصة الأصلية. نحن ننتقي بعناية أفضل الأدوات في العالم للارتقاء بطقوس القهوة اليومية.",
    connect: "تواصل معنا",
    visitUs: "قم بزيارتنا",
    viewProduct: "شراء المنتج",
    aboutSubtitle: "عن ديار سيلكشن",
    aboutTitle1: "مصنوعة من أجل",
    aboutTitle2: "أشخاص",
    aboutTitle3: "يعيشون للقهوة.",
    aboutP1: "تأسست ديار سيلكشن برسالة واحدة: تقديم أرقى أدوات القهوة المختصة في العالم لعشّاقها الذين لا يرضون إلا بالأفضل.",
    aboutP2: "نحن ننتقي بعناية كل منتج في مجموعتنا، ونتعامل مباشرة مع علامات تجارية مثل Fellow وTimemore وHario و1Zpresso لضمان الأصالة والجودة. كل أداة مختارة ليس فقط لوظيفتها، بل للتجربة التي تقدمها.",
    aboutP3: "التزامنا يتجاوز بيع المنتجات. نحن نبني مجتمعاً من محبي القهوة الذين يشاركوننا شغفنا بالكوب المثالي — والأدوات الفاخرة التي تجعله ممكناً.",
    aboutVal1Title: "تميز منتقى",
    aboutVal1Desc: "كل منتج في مجموعتنا تم اختياره يدوياً من قبل محترفي القهوة الذين يفهمون ما يجعل المعدات استثنائية حقاً.",
    aboutVal2Title: "أصالة مضمونة",
    aboutVal2Desc: "نعمل مباشرة مع العلامات التجارية والموزعين المعتمدين. كل منتج أصلي 100% مع ضمان كامل من الشركة المصنعة.",
    aboutVal3Title: "ثقة وشفافية",
    aboutVal3Desc: "توصيات صادقة. لا مساومة. نبيع فقط المنتجات التي نستخدمها شخصياً ونؤمن بها.",
    aboutVal4Title: "شغف في كل تفصيل",
    aboutVal4Desc: "نحن أكثر من مجرد متجر — نحن مجتمع يدفعه حب عميق للقهوة المختصة وطقوسها.",
    aboutJoin: "انضم إلى الآلاف من عشاق القهوة الذين يثقون في ديار سيلكشن.",
    getInTouch: "تواصل معنا",
    contactTitle1: "نحب أن",
    contactTitle2: "نسمع منك",
    phone: "الهاتف",
    phoneSub: "السبت - الأحد، 9 صباحاً - 8 مساءً",
    instagram: "إنستغرام",
    followUs: "تابعنا",
    whatsapp: "واتساب",
    chatWithUs: "تحدث معنا",
    quickResponse: "رد سريع",
    location: "الموقع",
    locationDetail: "السليمانية، كوردستان، العراق",
    visitOurStore: "زُر متجرنا",
    whatsappChat: "دردشة واتساب",
    slemaniLocation: "السليمانية، كوردستان",
    iraq: "العراق",
    searchCollection: "ابحث في مجموعتنا...",
  },
  ku: {
    home: "سەرەکی",
    products: "بەرهەمەکان",
    brands: "براندەکان",
    brewing_guide: "ئامادەکردن",
    news: "زانیاری",
    premiumCoffeeEquipment: "کەرەستەی قاوەی نایاب",
    collections: "کۆکراوەکان",
    about: "دەربارە",
    contact: "پەیوەندی",
    search: "گەڕان...",
    searchProducts: "گەڕان بۆ بەرهەمەکان...",
    bestSellers: "کۆکراوەی تایبەت",
    curatedSelection: "هەڵبژاردەی ئێمە",
    curatedSelectionDesc: "ئامراز و پێداویستییەکانی قاوە کە بە وریاییەوە لە باشترین براندەکانی جیهان هەڵبژێردراون بدۆزەوە.",
    exploreAll: "هەموو کۆکراوەکان ببینە",
    addToCart: "زیادکردن بۆ سەبەتە",
    orderWhatsApp: "داواکردن لەڕێگەی واتساپ",
    orderWithDetails: "داواکردنی ڕاستەوخۆ لە ڕێگەی واتسئاپ (پارە دان لە کاتی گەیاندن)",
    payOnlineCard: "پارەدانی ئۆنلاین (کارت)",
    orderModalDesc: "تکایە ناونیشان و ژمارەی مۆبایلی خۆت بنووسە بۆ ناردنی داواکارییەکەت لە ڕێگەی واتساپ. پارەدان بە کاش دەبێت لە کاتی وەرگرتنی داواکارییەکەت.",
    quickOrderWhatsApp: "کڕینی خێرا لەڕێگەی واتساپ",
    directOrderNoDetails: "گفتوگۆی ڕاستەوخۆ",
    fullName: "ناوی تەواو",
    phoneNumber: "ژمارەی مۆبایل",
    city: "شار / ناوچە",
    address: "ناونیشانی تەواو",
    cancel: "پاشگەزبوونەوە",
    confirmOrder: "ناردنی داواکاری لەڕێگەی واتساپ",
    fillAllFields: "تکایە هەموو خانەکان پڕبکەرەوە",
    inStock: "بەردەستە",
    outOfStock: "بەردەست نییە",
    soldOut: "نەماوە",
    bestSeller: "باشترین فرۆشراو",
    newArrival: "نوێ",
    reviews: "پێداچوونەوەکان",
    relatedProducts: "بەرهەمە پەیوەندیدارەکان",
    youMayAlsoLike: "ئەمانەش بەدڵت دەبن",
    description: "وەسف",
    allRightsReserved: "هەموو مافەکان پارێزراون.",
    language: "زمان",
    english: "English",
    arabic: "العربية",
    kurdish: "کوردی",
    heroTitlePart1: "باشترینەکان",
    heroTitlePart2: "",
    heroTitlePart3: "هەڵدەبژێرین",
    heroTitlePart4: "",
    heroSubtitle: "هەڵبژاردنی کەرەستەی دروستکردنی قاوە و شێوازەکانی ئامادەکردنی قاوە لەسەر بنەمای ئەزموون، زانست، ستانداردە جیهانییەکان.",
    exploreCollection: "کۆکراوەکان ببینە",
    watchOurStory: "چیرۆکەکەمان ببینە",
    typesOfCoffee: "جۆرەکانی ئامادەکردنی قاوە",
    exploreMethods: "جۆرە جیاوازەکانی ئامادەکردن تاقیبکەرەوە بۆ دۆزینەوەی باشترین کوپ بۆ تامی خۆت.",
    shopTools: "کڕینی ئامرازەکان",
    newsletter: "نامەنامە",
    newsletterDesc: "بەشداربە بۆ وەرگرتنی نوێکارییەکان و ئۆفەرە تایبەتەکان.",
    subscribe: "بەشداربوون",
    quickLinks: "بەستەرە خێراکان",
    contactUs: "پەیوەندیمان پێوە بکە",
    yourWishlistEmpty: "لیستی دڵخوازەکانت خاڵییە",
    wishlistEmptyDesc: "پێدەچێت هێشتا هیچ بەرهەمێکت پاشەکەوت نەکردبێت. کۆکراوەکانمان ببینە و کرتە لە ئایکۆنی دڵ بکە بۆ پاشەکەوتکردن.",
    exploreProducts: "بەرهەمەکان ببینە",
    myWishlist: "دڵخوازەکانم",
    savedProducts: "ئەو بەرهەمانەی پاشەکەوتت کردوون.",
    items: "دانە",
    item: "دانە",
    noProductsFound: "هیچ بەرهەمێک نەدۆزرایەوە",
    tryAdjusting: "هەوڵبدە گەڕانەکەت یان پۆلێنەکەت بگۆڕیت.",
    filter: "پاڵاوتن:",
    allCategories: "هەموو پۆلێنەکان",
    allProducts: "هەموو بەرهەمەکان",
    allProductsDesc: "کۆکراوەی تەواوی ئامراز و بەرهەمە نایابەکانی قاوەمان ببینە.",
    footerDesc: "دیار سێلێکشن باشترین شوێنە بۆ ئامرازە ڕەسەنەکانی قاوەی تایبەت. ئێمە بەوردی باشترین ئامرازەکانی جیهان هەڵدەبژێرین بۆ بەرزکردنەوەی ئاستی قاوەی ڕۆژانەت.",
    connect: "پەیوەندی",
    visitUs: "سەردانمان بکە",
    viewProduct: "کڕینی بەرهەم",
    aboutSubtitle: "دەربارەی دیار سێلێکشن",
    aboutTitle1: "دروستکراوە بۆ",
    aboutTitle2: "ئەو کەسانەی",
    aboutTitle3: "بۆ قاوە دەژین.",
    aboutP1: "دیار سێلێکشن بە ئامانجێکی تاکەوە دامەزرا: هێنانی باشترین ئامرازەکانی قاوەی تایبەتی جیهان بۆ ئەو قاوە خۆشەویستانەی کە تەنها باشترینیان دەوێت.",
    aboutP2: "ئێمە بەوردی هەموو بەرهەمێکی کۆکراوەکەمان هەڵدەبژێرین، ڕاستەوخۆ لەگەڵ براندەکانی وەکوو Fellow و Timemore و Hario و 1Zpresso کاردەکەین بۆ دڵنیابوون لە ڕەسەنی و کوالیتی. هەموو ئامرازێک تەنها بۆ کارەکەی هەڵنەبژێردراوە، بەڵکوو بۆ ئەو ئەزموونەی دروستی دەکات.",
    aboutP3: "پابەندبوونی ئێمە لە فرۆشتنی بەرهەمەکان دەپەڕێتەوە. ئێمە کۆمەڵگەیەکی قاوە خۆشەویستان دروست دەکەین کە ئارەزووی کوپی تەواو لەگەڵمان هاوبەشە — و ئەو ئامرازە نایابانەی کە دەیکەنە ڕاستی.",
    aboutVal1Title: "نایابی هەڵبژێردراو",
    aboutVal1Desc: "هەموو بەرهەمێکی کۆکراوەکەمان بە دەست پسپۆڕانی قاوە هەڵبژێردراوە کە تێدەگەن چی ئامرازێک ڕاستی نایابە.",
    aboutVal2Title: "ڕەسەنی گەرەنتیکراو",
    aboutVal2Desc: "ڕاستەوخۆ لەگەڵ براندەکان و دابەشکەرە ڕەسمییەکان کاردەکەین. هەموو بەرهەمێک ١٠٠٪ ئۆریجیناڵە بە گەرەنتی تەواوی کارگە.",
    aboutVal3Title: "متمانە و ڕوونی",
    aboutVal3Desc: "پێشنیاری ڕاستگۆیانە. بێ سازش. تەنها ئەو بەرهەمانە دەفرۆشین کە خۆمان بەکاری دەهێنین و بڕوامان پێیەتی.",
    aboutVal4Title: "ئارەزوو لە هەموو وردەکارییەک",
    aboutVal4Desc: "ئێمە زیاترین لە فرۆشگایەک — ئێمە کۆمەڵگەیەکیین کە بە خۆشەویستییەکی قووڵ بۆ قاوەی تایبەت و ڕێوڕەسمەکانی دەوری دەجوڵێین.",
    aboutJoin: "بەشداربە لەگەڵ هەزاران قاوە خۆشەویست کە متمانەیان بە دیار سێلێکشن هەیە.",
    getInTouch: "پەیوەندیمان پێوە بکە",
    contactTitle1: "دەمانەوێت",
    contactTitle2: "گوێمان لێت بێت",
    phone: "تەلەفۆن",
    phoneSub: "شەممە - یەکشەممە، ٩ بەیانی - ٨ ئێوارە",
    instagram: "ئینستاگرام",
    followUs: "شوێنمان بکەوە",
    whatsapp: "واتساپ",
    chatWithUs: "قسەمان لەگەڵ بکە",
    quickResponse: "وەڵامی خێرا",
    location: "شوێن",
    locationDetail: "سلێمانی، کوردستان، عێراق",
    visitOurStore: "سەردانی فرۆشگاکەمان بکە",
    whatsappChat: "گفتوگۆی واتساپ",
    slemaniLocation: "سلێمانی، کوردستان",
    iraq: "عێراق",
    searchCollection: "لە کۆکراوەکانمان بگەڕێ...",
  },
  kmr: {
    home: "Serekî",
    products: "Berhem",
    brands: "Brand",
    brewing_guide: "Amadekirin",
    news: "Zanyarî",
    premiumCoffeeEquipment: "Keresteyên Qahwê yên Taybet",
    collections: "Koleksiyon",
    about: "Derbarê Me",
    contact: "Pêwendî",
    search: "Lêgerîn...",
    searchProducts: "Lêgerîna berheman...",
    bestSellers: "Koleksiyona Taybet",
    curatedSelection: "Hildibijêrîna Diar",
    curatedSelectionDesc: "Amraz û keresteyên qahwê yên herî mezin ji brandên navdar ên cîhanê bistînin.",
    exploreAll: "Hemû Koleksiyonê Bibîne",
    addToCart: "Zêde bike bo Sebetê",
    orderWhatsApp: "Sipariş bi rêya WhatsApp",
    orderWithDetails: "Sipartina Rasterast (Pay bi Cash li Dema Gihandinê)",
    payOnlineCard: "Pêdana serhêl (Kart)",
    orderModalDesc: "Ji kerema xwe navnîşan û hejmara telefona xwe binivîse bo şandina sipartinê bi rêya WhatsApp. Paşê teqdîmkirina drav bi cash li dema wergirtina sipartinê ye.",
    quickOrderWhatsApp: "Kirîna Xêra",
    directOrderNoDetails: "Peywendiya Rastrast",
    fullName: "Nav û Paşnav",
    phoneNumber: "Hejmara Telefonê",
    city: "Bajar / Herêm",
    address: "Navnîşana Teqez",
    cancel: "Betal bike",
    confirmOrder: "Siparişê bi WhatsApp bişîne",
    fillAllFields: "Ji kerema xwe hemû cihan tije bikin",
    inStock: "Li Embarê Heye",
    outOfStock: "Nîne",
    soldOut: "Qediya",
    bestSeller: "Yê Herî Firotî",
    newArrival: "NÛ",
    reviews: "nirxandin",
    relatedProducts: "Berhemên Pêwendîdar",
    youMayAlsoLike: "Ew tiştên ku dibe ku ji we re xweş bin",
    description: "Danasîn",
    allRightsReserved: "Hemû maf parastî ne.",
    language: "Ziman",
    english: "English",
    arabic: "العربية",
    kurdish: "کوردی (سۆرانی)",
    kurdishKurmanji: "کوردی (کرمانجی)",
    heroTitlePart1: "Em Hilbijêrin",
    heroTitlePart2: "",
    heroTitlePart3: "Yên Herî Baş",
    heroTitlePart4: "",
    heroSubtitle: "Hildibijêrina keresteyên amadekirina qahwê û rêbazên amadekirina qahwê li ser bingeha ezmûn, zanist û standardên cîhanî.",
    exploreCollection: "Koleksiyonê Bibîne",
    watchOurStory: "Çîroka Me Bibîne",
    typesOfCoffee: "Cûreyên Amadekirina Qahwê",
    exploreMethods: "Rêbazên cuda yên amadekirina qahwê bibînin ji bo qahweya herî baş.",
    shopTools: "Amrazan Bikire",
    newsletter: "Nûçename",
    newsletterDesc: "Tevbê nûçenameyê bibe ji bo agahdariyên nû û pêşniyarên taybet.",
    subscribe: "Tevbê bibe",
    quickLinks: "Girêdanên Xêra",
    contactUs: "Pêwendî bi me re",
    yourWishlistEmpty: "Lîsteya daxwazên te vala ye",
    wishlistEmptyDesc: "Te ti berhem lê zêde nekiriye.",
    exploreProducts: "Berheman Bibîne",
    myWishlist: "Lîsteya Min a Daxwazê",
    savedProducts: "Berhemên ku te tomar kirine.",
    items: "berhem",
    item: "berhem",
    noProductsFound: "Ti berhem nehat dîtin",
    tryAdjusting: "Lêgerîna xwe biguherîne.",
    filter: "Fîlter:",
    allCategories: "Hemû Kategorî",
    allProducts: "Hemû Berhem",
    allProductsDesc: "Koleksiyona me ya amraz û keresteyên qahwê yên premium bibîne.",
    footerDesc: "Diar Selection cîhê taybet e bo amraz û keresteyên qahwê yên orjînal ên cîhanê.",
    connect: "Pêwendî",
    visitUs: "Serdana me bike",
    viewProduct: "Berhemê Bikire",
    aboutSubtitle: "Derbarê Diar Selection",
    aboutTitle1: "Zevkiya",
    aboutTitle2: "Mirovên ku",
    aboutTitle3: "Ji Qahwê re Dijîn.",
    aboutP1: "Diar Selection bi armanca anîna amrazên qahwê yên herî baş hatiye damezrandin.",
    aboutP2: "Em bi brandên navdar ên cîhanê re kar dikin ji bo dabînkirina qalîteya bilind.",
    aboutP3: "Armanca me avakirina civakeke ji hezkiriyên qahwê ye.",
    aboutVal1Title: "Hildibijêrîna Baş",
    aboutVal1Desc: "Hemû berhem ji aliyê pisporên qahwê ve hatine hilbijartin.",
    aboutVal2Title: "Orjînaliya Misoger",
    aboutVal2Desc: "Em rasterast bi belavkerên fermî re kar dikin.",
    aboutVal3Title: "Bawerî û Şeffafî",
    aboutVal3Desc: "Pêşniyarên rast û zelal.",
    aboutVal4Title: "Hûrgiliyên Baş",
    aboutVal4Desc: "Ji bo ceribandina qahweya herî baş.",
    aboutJoin: "Tevbê hezaran hezkiriyên qahwê bibe.",
    getInTouch: "Pêwendî bi me re",
    contactTitle1: "Em dixwazin",
    contactTitle2: "Bihîzin ji te",
    phone: "Telefon",
    phoneSub: "Şemî - Yekşemî, 9 sibehê - 8 êvarê",
    instagram: "Instagram",
    followUs: "Me bişopîne",
    whatsapp: "WhatsApp",
    chatWithUs: "Peywendî bi me re",
    quickResponse: "Bersiva xêra",
    location: "Cih",
    locationDetail: "Silêmanî, Kurdistan, Êraq",
    visitOurStore: "Serdana dikana me bike",
    whatsappChat: "Axaftina WhatsApp",
    slemaniLocation: "Silêmanî, Kurdistan",
    iraq: "Êraq",
    searchCollection: "Di koleksiyonê de bigere...",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ku");

  useEffect(() => {
    // If previously saved as 'en' in localStorage, reset to Kurdish default
    const localLang = localStorage.getItem("diar_language");
    if (localLang === "en") {
      localStorage.removeItem("diar_language");
    }

    // Check session language; default to Kurdish ('ku') for new visits/tabs
    const savedLang = (sessionStorage.getItem("diar_language") || localStorage.getItem("diar_language")) as Language;
    if (savedLang && ["en", "ar", "ku", "kmr"].includes(savedLang) && savedLang !== "en") {
      setLanguageState(savedLang);
    } else {
      setLanguageState("ku");
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    sessionStorage.setItem("diar_language", lang);
    localStorage.setItem("diar_language", lang);
  };

  const dir = language === "ar" || language === "ku" || language === "kmr" ? "rtl" : "ltr";

  const t = (key: keyof typeof translations.en) => {
    const val = translations[language]?.[key];
    if (val !== undefined) return val;
    return translations.ku[key] !== undefined ? translations.ku[key] : translations.en[key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, dir, t }}>
      <div dir={dir} data-lang={language} className={dir === "rtl" ? "font-serif-ar" : ""}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
